name: Deploy to Amazon S3

on:
  push:
    branches:
      - main # Set to your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check Out Repository
      uses: actions/checkout@v2

    - name: Set Up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Build Frontend
      run: |
        cd frontend
        npm install
        npm run build
      env:
        VITE_BACKEND_URL: ${{ secrets.VITE_BACKEND_URL }}

    - name: Deploy to S3
      uses: jakejarvis/s3-sync-action@v0.5.1
      with:
        args: --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'eu-west-2'
        SOURCE_DIR: 'frontend/dist/'
